<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>firstDecision</name>
  <uuid>4e21ea38-8d72-4b5f-8689-2b5f0537fc6f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Response where
		the message is "successful" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
